# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing

__all__ = [
    "PyTable",
    "apply_styles",
    "register_command",
    "run_cli",
]

@typing.final
class PyTable:
    r"""
    Formats a table from Python data.
    """
    def __new__(cls) -> PyTable: ...
    def add_row(self, py_row: typing.Sequence[builtins.str]) -> None:
        r"""
        Add a row to the table.
        Expects a list of strings for now.
        """
    def to_string(self) -> builtins.str:
        r"""
        Returns the table as a formatted string.
        """

def apply_styles(text: builtins.str) -> builtins.str: ...
def register_command(
    name: str,
    func: typing.Any,
    doc: str | None = None,
    params: list[dict[str, typing.Any]] = ...,
) -> None: ...
def run_cli(args: list[str]) -> None: ...
